// Array Function

// const add = (num1, num2) => num1 * num2;
// const sum = add(20, 30)

// const added = (num1, num2, num3) => num1 * num2 * num3;
// const summs = added(9, 7, 6) 

// const newNumber = (num1) => num1 *20;
// const result = newNumber(9);

// const singleNum = num1 => num1*23;
// const ning = singleNum(2)

// const myNmae = () => 'samim Shammo'
// const onna = myNmae()
// // console.log(sum, summs, result, ning, onna);

// const doMath = (x,y) =>{
//         const result = x * y;
//         const plus = x + y;
//         const mainus = x - y;
//         const moy = plus * mainus;
//         const newONe = moy *5;
//         return newONe;

// }
// const allElement = doMath(8, 6)
// // console.log(allElement);

// const array = [34, 23, 54, 24, 64, 21, 'samim', 'sakib'];
// // console.log(array)
// // console.log(...array)

// const numbers = [45, 12, 36, 84]
// numbers.unshift(25)
// console.log(numbers)
// function getSum(a, b=9){return a+b;} console.log(getSum(2, 7));

// const y = x => x*x;
// const x = y(5); 
// console.log(x);
// const name = 'Hero'; 
// // const greetings = 'Welcome Home!'+' '+name;
// // const greetings= `Welcome Home! ${name}`
// const greetings= `${2+3}`
// // console.log(greetings)
// const mYfunc= ()=> console.log('nayok!')
// const  division=  num1, num2 => console.log(num1 /num2)
const numbers=[10,20,30,40,50,60,70 ]

const newNUm = Math.max(...numbers)
// console.log(newNUm)
const cars=['toyota', 'honda','mercedes']; 
const newCars= [...cars , 'ferrari'];
console.log(newCars)


